version: "3.8"
services:
  postgres:
    image: postgres:15-alpine
    container_name: lets-go-fly-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lets_go_fly
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: lets-go-fly-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  pgdata:

