name: Web CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ cursor/** ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            apps/web/package-lock.json

      - name: Install dependencies (web)
        working-directory: apps/web
        run: npm ci

      - name: Install Playwright browsers and deps
        working-directory: apps/web
        run: npx playwright install --with-deps

      - name: Lint
        working-directory: apps/web
        run: npm run lint

      - name: Build
        working-directory: apps/web
        run: npm run build

      - name: Run e2e tests
        working-directory: apps/web
        env:
          E2E_BASE_URL: http://127.0.0.1:3000
        run: |
          npx concurrently -k -s first -n WEB,TEST "npm run start" "wait-on http://127.0.0.1:3000 && npm run e2e"

